travis:
  secure:
    BINSTAR_TOKEN: W41r37zyUCQq/tqVxrV+WHnk/jOZoZgJFCzonWf+DOIAViNVHwJpEbBsaaMasK2bDt6y2mfuHQwwuKP/ZDMPXeAc8V7GbJ4sioGk6/RBrYxZr079b5HuC3i4lLWgiusn8b8DSv2lmDrCCnVYplTleXtQUCLMGYP+sbYc0p0wbvjZK8PfqVOqMyOXQNPrOvu0ZSg+NptGCKaTF4VVY5giEMlXJR9AZpZe/5dr8vKT3ApdMVMO8Yj+puJy5ovV5LbQ6TMCxu31UpakBDJveA3Z+tm/Vn+tRCiv0fmdLSILGLKELAI5ixF9FGl9vEPcrODsAB01dOLnLiM4KfxBWUNCfP4HwDbp5zIZfrNCHcPIjysHNOu1oLaoknQwUMadfwXDAD4P8yHCv3kTmPCYq3TzNEBFdMhFtsqI85bJgG1VzXy12zRf1TN7NFfzfjjwJ6nfYSF1Snhhtg/7HVtaWxO8dv8Tir0UCSD/L/dniuUGHsjhhBUUVz0fgRM7yYLzLdqhtk9vzRyA0zQoSH3UOUFUVjGnXsMqqbaGF/9/TiOz4X4V/11adBz5OrnvXzVUMaZMAtdzUUjVEPZPa0p7o+lPRZVmbZJyh0sjCIlSiDPyFgCjK+OZ1J3778XizYwG4IQvjOMpxOYvJ5THAlDecuJwGodFFUGxazCZjIf+FRIIM/g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
