travis:
  secure:
    BINSTAR_TOKEN: eh9WJdUai7HQUBtKYVkeGNMImxoxQc/k7DzADPZ2kWtfml1pYCNF4hR/0odZBEjFosdRTvCLgXtr22RNkVtsXodH8aPgIdJv12wsWh3ucXCq1sMyi//w68EOVa8awnjaoN0Mh/MaCxTapEvT52f8bqyEgvuez5dGw+0Gl9XLULp2bENU2Se0HJHwLqzP34zx/cSlVYognxOBLxq/9r0/d3K6MPA87iC5AdBtHtxMSzPjb3Sx+AqlrA/T0gNbuDfHVmilGnlopMUxeFiV09xiI32fwNTaTGZmrK9wRUlUoWULmpgLd+x5GVilKYynYU8vG6Bf5Z+scx51Rg8lPLMi6lc2FOYQmOhYxVwsj4WfcX54Z6do6XGVIYCx8hVnRiYHp6znuTSX4YbKCb/1yo6Q7sCMudO+3hmoAJB6DJqeByhNr9E2WJCV2FcWn1kFw1AvBoCWf9x9BspNgyr0vhCZaWIbAk1MkB8RDJeFVUyTU2N8EhgnHqmjZf8+73+OpLx9VKNVUshnzLK1ipklSoALjwA5AKYZqJ3j84iuI3BSJFfFr+bisMx16cGnREWU2dgzMiX9Z5sHcQlLck6R1bVd2BC7vFepU11zRi0uEw4U+TOeq+iem4p4BJOqRsZqOnM/38Gh+GvUXfRQGy0e8YhM+9rjFOl5cUDabluQVwjQE98=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
